#!/bin/bash
# chkconfig: 3 90 20
# description: Startup/Shutdown TIBCO BusinessWorks Agent
source $( dirname "$0" )/config.sh

case "$1" in
 	start)
	 	inf "Starting Postgres Database"
		postgres_pid=`ps -ef | grep "bin/postgres" | grep -v "grep"  | awk '{print $2}'`
		if [ -z $postgres_pid ]
		then
			/Applications/Postgres.app/Contents/Versions/9.6/bin/postgres -D "/Users/elghazali/Library/Application Support/Postgres/var-9.6" -p 5432 > $DIR/logs/postgres.log 2>&1 &
		else
			success "\t ✅ PostgreSQL database is started (PID: $postgres_pid)."
		fi

		inf "Starting TIBCO BusinessWorks Agent"
        bw_pid=`pidof bwagent`
		if [ -z $bw_pid ]
		then
			cd $BW_HOME/bin/
			$BW_HOME/bin/bwagent > $LOGFILE_BW 2>&1 &
			cd -
			warn '████			(33%)\r'
			sleep 2
			warn '████████      (66%)\r'
			sleep 2
			warn '████████████	(100%)\r'
			echo -ne '\n'
			tail -10 $LOGFILE_BW
			$0 status
		else 
			$0 status
		fi


	;;
	stop)
		inf "Stopping TIBCO BusinessWorks AppNode"
		for var in `find $BW_HOME -name "stopBWAppNode.sh"` 
		do 
			echo $var
			. $var 
		done 
		bw_pid=`pidof bwagent`
		if [ -z $bw_pid ]
		then
			error "No bwagent pid found. Nothing to stop... "
			exit 1
		fi
		kill $bw_pid >> $LOGFILE_BW 2>&1
		$0 status
	;;
	status)
		inf "Status of TIBCO BusinessWorks Agent"
		bw_pid=`pidof bwagent`
		if [ -z $bw_pid ]
		then
			error "\t ❌ TIBCO BW Agent is stopped."
		else
			success "\t ✅ TIBCO BW Agent is started (PID: $bw_pid)."
		fi

		inf "Status of TIBCO BusinessWorks Appnodes"
		bwappnode_pid=`pidof bwappnode`
		if [ -z $bwappnode_pid ]
		then
			error "\t ❌ TIBCO BW Appnode is stopped."
		else
			success "\t ✅ TIBCO BW Appnode is started (PID: $bwappnode_pid)."
		fi
	;;
	restart)
		$0 stop
		$0 start
	;;
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
	;;
esac
exit 0
																  
