#!/bin/bash
# chkconfig: 3 90 20
# description: Startup/Shutdown TIBCO BusinessWorks Agent
source $( dirname "$0" )/config.sh
inf "➡️  Working in $BW_HOME"
case "$1" in
 	start)
	 	inf "Starting Postgres Database"
		postgres_pid=`ps -ef | grep "bin/postgres" | grep -v "grep"  | awk '{print $2}'`
		if [ -z $postgres_pid ]
		then
			postgres_pid=`brew services run postgresql`
		else
			success "PostgreSQL database is started (PID: $postgres_pid)."
		fi

		inf "Starting TIBCO BusinessWorks Agent"
        bw_pid=`pidof bwagent`
		if [ -z $bw_pid ]
		then
			cd $BW_HOME/bin/
			$BW_HOME/bin/bwagent apiserver> $LOGFILE_BW 2>&1 &
			cd -
			timer
			tail -10 $LOGFILE_BW
			$0 status
		else 
			$0 status
		fi


	;;
	stop)
		inf "Stopping TIBCO BusinessWorks AppNodes"
		for var in `find $BW_HOME -name "stopBWAppNode.sh"` 
		do 
			echo $var
			. $var 
		done 
		bw_pid=`pidof bwagent`
		if [ -z $bw_pid ]
		then
			error "No bwagent pid found. Nothing to stop... "
			exit 1
		fi
		cd $BW_HOME/bin/
		$BW_HOME/bin/bwagent stop> $LOGFILE_BW 2>&1 &
		$0 status
	;;
	status)
		inf "Status of TIBCO BusinessWorks Agent"
		bw_pid=`pidof bwagent`
		if [ -z $bw_pid ]
		then
			error "TIBCO BW Agent is stopped."
		else
			success "TIBCO BW Agent is started (PID: $bw_pid)."
		fi

		inf "Status of TIBCO BusinessWorks Appnodes"
		bwappnode_pid=`pidof bwappnode`
		if [ -z $bwappnode_pid ]
		then
			error "TIBCO BW Appnode is stopped."
		else
			success "TIBCO BW Appnode is started (PID: $bwappnode_pid)."
		fi
	;;
	restart)
		$0 stop
		$0 start
	;;
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
	;;
esac
exit 0
																  
