#!/bin/bash

# chkconfig: 3 90 20
# description: Startup/Shutdown TIBCO EMS
source config.sh

case "$1" in
 	start)
		inf "Starting TIBCO EMS Instance"
			cd $EMS_HOME/bin/
		    $EMS_HOME/bin/tibemsd64 > $LOGFILE_EMS 2>&1 &
            cd -
		    echo -ne '#####                     (33%)\r'
		    sleep 2
		    echo -ne '#############             (66%)\r'
		    sleep 2
		    echo -ne '#######################   (100%)\r'
		    echo -ne '\n'
		    $0 status	
		;;
 	stop)
        inf "Stopping TIBCO EMS Instance"
	    ems_pid=`pidof tibemsd`
		if [ -z $ems_pid ]
		then
			error "No EMS pid found. Nothing to stop... "
			exit 1
		fi
		kill $ems_pid >> $LOGFILE_EMS 2>&1
		$0 status
		;;
	status)
        inf "Status of TIBCO EMS Instance"
        ems_pid=`pidof tibemsd`
		if [ -z $ems_pid ]
	    	then
			error "\t ❌ TIBCO EMS Instance is stopped"
		else
			success "\t ✅ TIBCO EMS Instance is started (PID: $ems_pid)"
	    	fi
		;;
	restart)
		$0 stop
        sleep 2
   		$0 start
	  	;;
  *)
		inf "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac
exit 0
																  
