#!/bin/bash

# chkconfig: 3 90 20
# description: Startup/Shutdown TIBCO TEA
source config.sh

case "$1" in
 	start)
		inf "Starting TIBCO TEA Agent"
			cd $TEA_HOME/bin/
		    $TEA_HOME/bin/tea > $LOGFILE_TEA 2>&1 &
            cd -
		    echo -ne '#####                     (33%)\r'
		    sleep 2
		    echo -ne '#############             (66%)\r'
		    sleep 2
		    echo -ne '#######################   (100%)\r'
		    echo -ne '\n'
		    $0 status	
		;;
 	stop)
        inf "Stopping TIBCO TEA Agent"
	    tea_pid=`ps -ef | grep "tea --innerProcess" | grep -v "grep"  | awk '{print $2}'`
		if [ -z $tea_pid ]
	    	then
			error "No TEA pid found. Nothing to stop... "
	    	exit 1
	    	fi
		kill $tea_pid >> $LOGFILE_TEA 2>&1
		sleep 2
		$0 status
		;;
	status)
        inf "Status of TIBCO TEA Agent"
        tea_pid=`ps -ef | grep "tea --innerProcess" | grep -v "grep"  | awk '{print $2}'`
		if [ -z $tea_pid ]
	    	then
			error "\t ❌ TIBCO TEA Agent is stopped."
		else
			success "\t ✅ TIBCO TEA Agent is started (PID: $tea_pid)."
	    	fi
		;;
	restart)
		$0 stop
        sleep 2
   		$0 start
	  	;;
  *)
		inf "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac
exit 0
																  
