#!/bin/bash

# chkconfig: 3 90 20
# description: Startup/Shutdown TIBCO BusinessWorks Agent
function log() {
	# Text color variables
	txtund=$(tput sgr 0 1)          # Underline
	txtbld=$(tput bold)             # Bold
	bldred=${txtbld}$(tput setaf 1) #  red
	bldylw=${txtbld}$(tput setaf 3) #  red
	bldblu=${txtbld}$(tput setaf 2) #  blue
	bldwht=${txtbld}$(tput setaf 7) #  white
	txtrst=$(tput sgr0)             # Reset
	info=${bldwht}*${txtrst}        # Feedback
	pass=${bldblu}*${txtrst}
	warn=${bldred}*${txtrst}
	ques=${bldblu}?${txtrst}


case "$1" in
 	INFO)
		echo -e "$bldwht$2$txtrst"
	;;
	ERROR)
		echo -e "$bldred$2$txtrst"
	;;
	WARN)
		echo -ne "$bldylw$2$txtrst"
	;;
	SUCCESS)
		echo -e "$bldblu$2$txtrst"
	;;
	*)
		echo -e "$bldwht$2$txtrst"
	;;
esac
}

error() { log ERROR "$1"; }
warn() { log WARN "$1"; }
success() { log SUCCESS "$1"; }
inf() { log INFO "$1"; } # "info" is already a command


# Set environment variables
export DIR="$( cd "$( dirname "$0" )" && pwd )"
export TIBCO_HOME=/opt/tibco/home/BW650
export BW_HOME=$TIBCO_HOME/bw/6.5
export LOGFILE=$DIR/logs/tibco-bwagent_out.log

case "$1" in
 	start)
	 	inf "Starting Postgres Database"
		postgres_pid=`ps -ef | grep "bin/postgres" | grep -v "grep"  | awk '{print $2}'`
		if [ -z $postgres_pid ]
		then
			/Applications/Postgres.app/Contents/Versions/9.6/bin/postgres -D "/Users/elghazali/Library/Application Support/Postgres/var-9.6" -p 5432 > $DIR/logs/postgres.log 2>&1 &
		else
			success "\t* PostgreSQL database is started (PID: $postgres_pid)."
		fi

		inf "Starting TIBCO BusinessWorks Agent"
        bw_pid=`pidof bwagent`
		if [ -z $bw_pid ]
		then
			cd $BW_HOME/bin/
			$BW_HOME/bin/bwagent > $LOGFILE 2>&1 &
			cd -
			warn '#####                     (33%)\r'
			sleep 2
			warn '#############             (66%)\r'
			sleep 2
			warn '#######################   (100%)\r'
			echo -ne '\n'
			tail -10 $LOGFILE
			$0 status
		else 
			success "\t* TIBCO BW Agent is already started (PID: $bw_pid)."
		fi


	;;
	stop)
		inf "Stopping TIBCO BusinessWorks Agent"
		for var in `find $TIBCO_HOME -name "stopBWAppNode.sh"` 
		do 
			echo $var
			. $var 
		done 
			bw_pid=`pidof bwagent`
		if [ -z $bw_pid ]
		then
			error "No bwagent pid found. Nothing to stop... "
			exit 1
		fi
		kill $bw_pid >> $LOGFILE 2>&1
		error "TIBCO BWAgent - stopped ! (PID: $bw_pid)."
	;;
	status)
		inf "Status of TIBCO BusinessWorks Agent"
		bw_pid=`pidof bwagent`
		if [ -z $bw_pid ]
		then
			error "\t ❌ TIBCO BW Agent is stopped."
		else
			success "\t ✅ TIBCO BW Agent is started (PID: $bw_pid)."
		fi

		inf "Status of TIBCO BusinessWorks Appnodes"
		bwappnode_pid=`pidof bwappnode`
		if [ -z $bwappnode_pid ]
		then
			error "\t ❌ TIBCO BW Appnode is stopped."
		else
			success "\t ✅ TIBCO BW Appnode is started (PID: $bwappnode_pid)."
		fi
	;;
	restart)
		$0 stop
		$0 start
	;;
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
	;;
esac
exit 0
																  
